//
//  Strings.swift
//  Don't Be a Stranger
//
//  Created by Сергей Коршунов on 20.10.2019.
//  Copyright © 2019 Сергей Коршунов. All rights reserved.
//

import Foundation

var questionsArray = [
    NSLocalizedString("1. If you knew that in a year you would die, what would you change in your life?", comment: ""),
    NSLocalizedString("2. Why should your friends love and respect you?", comment: ""),
    NSLocalizedString("3. What is your biggest fear?", comment: ""),
    NSLocalizedString("4. What is the strangest secret you have ever kept?", comment: ""),
    NSLocalizedString("5. If you were given a chance to be born in another family, what would it be?", comment: ""),
    NSLocalizedString("6. What is more important for you to be heard or heard?", comment: ""),
    NSLocalizedString("7. Describe your life by the name of the song.", comment: ""),
    NSLocalizedString("8. What would you do if one morning you woke up and realized that you were the only person on earth?", comment: ""),
    NSLocalizedString("9. If you could fly into space, where would you go?", comment: ""),
    NSLocalizedString("10. What is the most striking childhood event you remember?", comment: ""),
    NSLocalizedString("11. What was the name of the girl / guy to whom you had the opportunity to experience a feeling of love for the first time?", comment: ""),
    NSLocalizedString("12. If you could go back in time and change one event, what would you change?", comment: ""),
    NSLocalizedString("13. What bird would you associate yourself with?", comment: ""),
    NSLocalizedString("14. Do you prefer to return for what is left at home and be late or not to return but to be in time?", comment: ""),
    NSLocalizedString("15. Who or what influenced your life views?", comment: ""),
    NSLocalizedString("16. If you were an artist and you would have to draw only one picture all your life, what would you depict on it?", comment: ""),
    NSLocalizedString("17. Would you save a man if you knew that he was a killer if he were in danger?", comment: ""),
    NSLocalizedString("18. What is the softest for you?", comment: ""),
    NSLocalizedString("19. What project would you like to realize in your life?", comment: ""),
    NSLocalizedString("20. What is family for you?", comment: ""),
    NSLocalizedString("21. How do you see the meaning of your life?", comment: ""),
    NSLocalizedString("22. Is there life outside planet Earth?", comment: ""),
    NSLocalizedString("23. How would you use your tame Gene?", comment: ""),
    NSLocalizedString("24. Is there life after death?", comment: ""),
    NSLocalizedString("25. What is the saying that sunk into the soul the most?", comment: ""),
    NSLocalizedString("26. Can there be many best friends?", comment: ""),
    NSLocalizedString("27. Which musical instrument do you like most?", comment: ""),
    NSLocalizedString("28. How often did you need something?", comment: ""),
    NSLocalizedString("29. If you could fly into space, where would you go?", comment: ""),
    NSLocalizedString("30. Are you afraid of moving to another city?", comment: ""),
    NSLocalizedString("31. Tea or coffee? Why?", comment: ""),
    NSLocalizedString("32. Could you leave your children to do what you love?", comment: ""),
    NSLocalizedString("33. What awaits humanity in the future?", comment: ""),
    NSLocalizedString("34. The worst pain in your life?", comment: ""),
    NSLocalizedString("35. The happiest moment in your life?", comment: ""),
    NSLocalizedString("36. A plane or a train? Why?", comment: ""),
    NSLocalizedString("37. Which animal do you consider your favorite?", comment: ""),
    NSLocalizedString("38. What is your favorite movie?", comment: ""),
    NSLocalizedString("39. Which of the 4 elements is your favorite?", comment: ""),
    NSLocalizedString("40. Would you be able to drop everything and leave for India for half a year?", comment: ""),
    NSLocalizedString("41. Mountains or the ocean? Why?", comment: ""),
    NSLocalizedString("42. Are you afraid of the dark, or that it hides?", comment: ""),
    NSLocalizedString("43. How often do you dream? Which one was the most memorable?", comment: ""),
    NSLocalizedString("44. Have you had lucid dreams?", comment: ""),
    NSLocalizedString("45. What do you consider the purpose of your life?", comment: ""),
    NSLocalizedString("46. Would you be a good parent?", comment: ""),
    NSLocalizedString("47. How much of your man starts to really grow up?", comment: ""),
    NSLocalizedString("48. How do you feel about relaxing in clubs?", comment: ""),
    NSLocalizedString("49. A glass of wine a day, is it bad or good?", comment: ""),
    NSLocalizedString("50. Do you like to be engaged in sports?", comment: ""),
    NSLocalizedString("51. Which book did you like the most?", comment: ""),
    NSLocalizedString("52. Which film left an imprint in your memory?", comment: ""),
    NSLocalizedString("53. Is it important to be successful in life?", comment: ""),
    NSLocalizedString("54. What does it mean to you to be rich?", comment: ""),
    NSLocalizedString("55. Have you been able to have surgery on a person?", comment: ""),
    NSLocalizedString("56. Have you ever saved a person from death?", comment: ""),
    NSLocalizedString("57. Was your life in real danger?", comment: ""),
    NSLocalizedString("58. What is your dream job?", comment: ""),
    NSLocalizedString("59. Which country can you name ideal?", comment: ""),
    NSLocalizedString("60. What period in the history of mankind do you like most?", comment: ""),
    NSLocalizedString("61. Could myths be real historical facts?", comment: ""),
    NSLocalizedString("62. Will people be able to stop the war completely?", comment: ""),
    NSLocalizedString("63. Will artificial intelligence take over the planet?", comment: ""),
    NSLocalizedString("64. Which name do you like most?", comment: ""),
    NSLocalizedString("65. Do you consider yourself happy?", comment: ""),
    NSLocalizedString("66. Are you a conflict person?", comment: ""),
    NSLocalizedString("67. The craziest action in your life?", comment: ""),
    NSLocalizedString("68. Have you run in the rain?", comment: ""),
    NSLocalizedString("69. Have you been swimming naked?", comment: ""),
    NSLocalizedString("70. Winter or summer? Why?", comment: "")
]

let rulesText = NSLocalizedString("The essence of the game is very simple - you must answer the questions of your interlocutor, as well as ask them to him. The questions are not complicated and help to quickly create contact between people. Turn over the cards in turn and do not forget to be open to your interlocutor.", comment: "")
