# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Qreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Qreator
  pod 'EFQRCode', '~> 5.1.3'
  pod 'SPAlert'
end
